name: testsuite

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*"
  pull_request:

jobs:

  check_extended_testing:
    name: "EXTENDED_TESTING set?"
    runs-on: ubuntu-latest

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"      
      # --------------------------------------------------------------------------------------------
      # cannot use secrets earlier as part of 'if:' condition
      - name: "Runs if EXTENDED_TESTING is set"
        env:
          EXTENDED_TESTING: ${{ secrets.EXTENDED_TESTING }}
          PR_TARGET_REPOSITORY: github.event.pull_request.head.repo.full_name == 'Perl/perl5' || github.repository == 'Perl/perl5'
          CURRENT_REPOSITORY: github.repository == 'Perl/perl5'
        run: |
          if [ -z "${EXTENDED_TESTING}" || "${PR_TARGET_REPOSITORY}" eq 'Perl/perl5' || "${CURRENT_REPOSITORY}" eq 'Perl/perl5' ]; then
            echo "[Warning] Only run this job when secrets.EXTENDED_TESTING is set. Stopping."
            exit 78
          fi
      - run: echo "Running EXTENDED_TESTING tests"
      # --------------------------------------------------------------------------------------------
      - run: echo "Done"
      - run: echo "${{ github.event.pull_request.head.repo.full_name }}"
      - run: echo "${{ github.repository }}"
